### ISSUE TITLE
Include lucene-backward-codecs in the all jar

### ISSUE THREAD

**Issue by trejkaz** [javasoze/clue#55]
The current released version only reads Lucene 5.0 indexes and not 5.4.

So I built master, figuring that Lucene 6 does support 5.4, but it turns out that it refuses to read it because it hasn't included the backwards compatibility jar.

```
Exception in thread "main" java.lang.IllegalArgumentException: Could not load codec 'Lucene54'.  Did you forget to add lucene-backward-codecs.jar?
```

**Comment by sabi0** [comment]
The codecs are actually included.
The missing part is to list them in `META-INF/services/org.apache.lucene.codecs.Codec`

This also applies to other services added in various Lucene jars.

The workaround is to use 'simple' distribution (bin + lib + clue.jar) instead of 'clue-all.jar'.

**Comment by javasoze** [comment]
#59
