### ISSUE TITLE
Dependency conflict problems: there are conflicting classes in io.dashbase.clue:clue:6.6.2-1.0.0

### ISSUE THREAD

**Issue by PandaMonkey** [javasoze/clue#61]
Hi, by analyzing your dependency tree in pom file and source code, we found that there are conflicting classes in io.dashbase.clue:clue:6.6.2-1.0.0. This means that several classes with the same names in different JARs, but they have different implementations.
Conflicting jar-pair: commons-beanutils: **commons-beanutils-core** :1.8.0:><commons-beanutils:**commons-beanutils**:1.7.0:
 JVM only load the classes present first on the classpath and shadow the other duplicate ones. So in different runnning evironment, if the dependency order of classpath reverses, then the program behaviors will be unpredictable. In extreme cases, the feature set in acturally loaded classes maybe the subset of the feature set really required by your project (frequent occurrences).  In this scenario, **NoSuchMethodError** or **NoSuchMethodExceptions** may occur at runtime. Please pay attention about that. The conflicting details are listed below. Hope this can help you. Thank! ^_^

===============projectPath->io.dashbase.clue:clue:6.6.2-1.0.0@D:\ws\release\clue-release-6.6.2-1.0.0\pom.xml

Risk for jar-pair:<commons-beanutils:commons-beanutils-core:1.8.0:><commons-beanutils:commons-beanutils:1.7.0:>
 **a) Methods that only exist in commons-beanutils:commons-beanutils-core:1.8.0::  [io.dashbase.clue:clue:6.6.2-1.0.0:->org.apache.hadoop:hadoop-common:2.7.2:->commons-configuration:commons-configuration:1.6:->commons-beanutils:commons-beanutils-core:1.8.0:]**
<org.apache.commons.beanutils.BasicDynaBean: java.util.Map getMap()>
<org.apache.commons.beanutils.BeanUtils: boolean initCause(java.lang.Throwable,java.lang.Throwable)>
<org.apache.commons.beanutils.BeanUtils: boolean getCacheFast(java.util.Map)>
<org.apache.commons.beanutils.BeanUtils: java.util.Map createCache()>
<org.apache.commons.beanutils.BeanUtils: void setCacheFast(java.util.Map,boolean)>
<org.apache.commons.beanutils.BeanUtilsBean: boolean initCause(java.lang.Throwable,java.lang.Throwable)>
<org.apache.commons.beanutils.BeanUtilsBean: java.lang.reflect.Method getInitCauseMethod()>
<org.apache.commons.beanutils.BeanUtilsBean: void <init>(org.apache.commons.beanutils.ConvertUtilsBean)>
<org.apache.commons.beanutils.BeanUtilsBean: java.lang.Object convert(java.lang.Object,java.lang.Class)>
<org.apache.commons.beanutils.ConvertUtils: java.lang.Object convert(java.lang.Object,java.lang.Class)>
<org.apache.commons.beanutils.ConvertUtils: org.apache.commons.beanutils.Converter lookup(java.lang.Class,java.lang.Class)>
<org.apache.commons.beanutils.ConvertUtilsBean: void registerStandard(boolean,boolean)>
<org.apache.commons.beanutils.ConvertUtilsBean: void register(boolean,boolean,int)>
<org.apache.commons.beanutils.ConvertUtilsBean: void registerPrimitives(boolean)>
<org.apache.commons.beanutils.ConvertUtilsBean: void registerOther(boolean)>
<org.apache.commons.beanutils.ConvertUtilsBean: void registerArrays(boolean,int)>
<org.apache.commons.beanutils.ConvertUtilsBean: void registerArrayConverter(java.lang.Class,org.apache.commons.beanutils.Converter,boolean,int)>
<org.apache.commons.beanutils.ConvertUtilsBean: org.apache.commons.beanutils.Converter lookup(java.lang.Class,java.lang.Class)>
<org.apache.commons.beanutils.ConvertUtilsBean: java.lang.Object convert(java.lang.Object,java.lang.Class)>
<org.apache.commons.beanutils.DynaProperty: int hashCode()>
<org.apache.commons.beanutils.DynaProperty: boolean equals(java.lang.Object)>
<org.apache.commons.beanutils.JDBCDynaClass: java.lang.String getColumnName(java.lang.String)>
<org.apache.commons.beanutils.JDBCDynaClass: java.lang.Object getObject(java.sql.ResultSet,java.lang.String)>
<org.apache.commons.beanutils.LazyDynaBean: org.apache.commons.logging.Log logger()>
<org.apache.commons.beanutils.LazyDynaMap: java.util.Map getMap()>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method internalGetMethod(java.lang.Class,java.lang.String,int)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.Class[] access$100()>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method getMethod(java.lang.Class,java.lang.String,int)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method getMethod(java.lang.Class,java.lang.String,java.lang.Class[])>
<org.apache.commons.beanutils.MethodUtils: java.lang.reflect.Method getAccessibleMethod(java.lang.Class,java.lang.reflect.Method)>
<org.apache.commons.beanutils.MethodUtils: java.lang.reflect.Method getCachedMethod(org.apache.commons.beanutils.MethodUtils$MethodDescriptor)>
<org.apache.commons.beanutils.MethodUtils: int clearCache()>
<org.apache.commons.beanutils.MethodUtils: java.lang.Object invokeStaticMethod(java.lang.Class,java.lang.String,java.lang.Object[],java.lang.Class[])>
<org.apache.commons.beanutils.MethodUtils: java.lang.Object invokeExactStaticMethod(java.lang.Class,java.lang.String,java.lang.Object)>
<org.apache.commons.beanutils.MethodUtils: float getTotalTransformationCost(java.lang.Class[],java.lang.Class[])>
<org.apache.commons.beanutils.MethodUtils: void setCacheMethods(boolean)>
<org.apache.commons.beanutils.MethodUtils: java.lang.Object invokeExactStaticMethod(java.lang.Class,java.lang.String,java.lang.Object[],java.lang.Class[])>
<org.apache.commons.beanutils.MethodUtils: void cacheMethod(org.apache.commons.beanutils.MethodUtils$MethodDescriptor,java.lang.reflect.Method)>
<org.apache.commons.beanutils.MethodUtils: java.lang.Object invokeExactStaticMethod(java.lang.Class,java.lang.String,java.lang.Object[])>
<org.apache.commons.beanutils.MethodUtils: java.lang.Object invokeStaticMethod(java.lang.Class,java.lang.String,java.lang.Object)>
<org.apache.commons.beanutils.MethodUtils: float getObjectTransformationCost(java.lang.Class,java.lang.Class)>
<org.apache.commons.beanutils.MethodUtils: java.lang.reflect.Method getAccessibleMethodFromSuperclass(java.lang.Class,java.lang.String,java.lang.Class[])>
<org.apache.commons.beanutils.MethodUtils: java.lang.Object invokeStaticMethod(java.lang.Class,java.lang.String,java.lang.Object[])>
<org.apache.commons.beanutils.MethodUtils: void setMethodAccessible(java.lang.reflect.Method)>
<org.apache.commons.beanutils.PropertyUtilsBean: java.lang.reflect.Method getWriteMethod(java.lang.Class,java.beans.PropertyDescriptor)>
<org.apache.commons.beanutils.PropertyUtilsBean: org.apache.commons.beanutils.expression.Resolver getResolver()>
<org.apache.commons.beanutils.PropertyUtilsBean: void setResolver(org.apache.commons.beanutils.expression.Resolver)>
<org.apache.commons.beanutils.PropertyUtilsBean: java.lang.reflect.Method getReadMethod(java.lang.Class,java.beans.PropertyDescriptor)>
<org.apache.commons.beanutils.PropertyUtilsBean: void setPropertyOfMapBean(java.util.Map,java.lang.String,java.lang.Object)>
<org.apache.commons.beanutils.PropertyUtilsBean: java.lang.Object getPropertyOfMapBean(java.util.Map,java.lang.String)>
<org.apache.commons.beanutils.PropertyUtilsBean: void <clinit>()>
<org.apache.commons.beanutils.ResultSetDynaClass: java.lang.Object getObjectFromResultSet(java.lang.String)>
<org.apache.commons.beanutils.WrapDynaClass: java.lang.Class getBeanClass()>
<org.apache.commons.beanutils.WrapDynaClass: java.util.Map access$000()>
<org.apache.commons.beanutils.WrapDynaClass: java.util.Map getDynaClassesMap()>
<org.apache.commons.beanutils.converters.AbstractArrayConverter: void <init>(java.lang.Object)>
<org.apache.commons.beanutils.converters.BigDecimalConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.BigDecimalConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.BigIntegerConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.BigIntegerConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.BooleanArrayConverter: void <init>(org.apache.commons.beanutils.converters.BooleanConverter,java.lang.Object)>
<org.apache.commons.beanutils.converters.BooleanArrayConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.BooleanConverter: void <init>(java.lang.String[],java.lang.String[],java.lang.Object)>
<org.apache.commons.beanutils.converters.BooleanConverter: void <clinit>()>
<org.apache.commons.beanutils.converters.BooleanConverter: java.lang.String[] copyStrings(java.lang.String[])>
<org.apache.commons.beanutils.converters.BooleanConverter: void <init>(java.lang.String[],java.lang.String[])>
<org.apache.commons.beanutils.converters.BooleanConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.BooleanConverter: java.lang.Object convertToType(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.BooleanConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.ByteConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.ByteConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.CharacterConverter: java.lang.Object convertToType(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.CharacterConverter: java.lang.String convertToString(java.lang.Object)>
<org.apache.commons.beanutils.converters.CharacterConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.CharacterConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.ClassConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.ClassConverter: java.lang.String convertToString(java.lang.Object)>
<org.apache.commons.beanutils.converters.ClassConverter: java.lang.Object convertToType(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.DoubleConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.DoubleConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.FileConverter: java.lang.Object convertToType(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.FileConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.FileConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.FloatConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.FloatConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.IntegerConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.IntegerConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.LongConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.LongConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.ShortConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.ShortConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.SqlDateConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.SqlDateConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.SqlTimeConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.SqlTimeConverter: java.text.DateFormat getFormat(java.util.Locale,java.util.TimeZone)>
<org.apache.commons.beanutils.converters.SqlTimeConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.SqlTimestampConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.SqlTimestampConverter: java.text.DateFormat getFormat(java.util.Locale,java.util.TimeZone)>
<org.apache.commons.beanutils.converters.SqlTimestampConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.StringConverter: void <init>(java.lang.Object)>
<org.apache.commons.beanutils.converters.StringConverter: java.lang.Object convertToType(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.StringConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.StringConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.URLConverter: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.converters.URLConverter: java.lang.Class getDefaultType()>
<org.apache.commons.beanutils.converters.URLConverter: java.lang.Object convertToType(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.locale.converters.BigDecimalLocaleConverter: java.lang.Object parse(java.lang.Object,java.lang.String)>
<org.apache.commons.beanutils.locale.converters.BigIntegerLocaleConverter: java.lang.Object parse(java.lang.Object,java.lang.String)>
<org.apache.commons.beanutils.locale.converters.DateLocaleConverter: java.lang.String convertLocalizedPattern(java.lang.String,java.util.Locale)>
<org.apache.commons.beanutils.locale.converters.DateLocaleConverter: java.lang.String convertPattern(java.lang.String,java.lang.String,java.lang.String)>
<org.apache.commons.beanutils.locale.converters.DateLocaleConverter: java.lang.String initDefaultChars()>
<org.apache.commons.beanutils.locale.converters.LongLocaleConverter: java.lang.Object parse(java.lang.Object,java.lang.String)>
<org.apache.commons.beanutils.locale.converters.ShortLocaleConverter: java.lang.Object parse(java.lang.Object,java.lang.String)>
 
  **b) Methods that only exist in commons-beanutils:commons-beanutils:1.7.0::  [io.dashbase.clue:clue:6.6.2-1.0.0:->org.apache.hadoop:hadoop-common:2.7.2:->commons-configuration:commons-configuration:1.6:->commons-digester:commons-digester:1.8:->commons-beanutils:commons-beanutils:1.7.0:]**
<org.apache.commons.beanutils.BeanUtilsBean: int findLastNestedIndex(java.lang.String)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: boolean throwsException(java.lang.reflect.Method,java.lang.Class)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method[] getPublicDeclaredMethods(java.lang.Class)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: boolean isSubclass(java.lang.Class,java.lang.Class)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method findMethod(java.lang.Class,java.lang.String,int)>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method findMethod(java.lang.Class,java.lang.String,int,java.lang.Class[])>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method internalFindMethod(java.lang.Class,java.lang.String,int,java.lang.Class[])>
<org.apache.commons.beanutils.MappedPropertyDescriptor: java.lang.reflect.Method internalFindMethod(java.lang.Class,java.lang.String,int)>
<org.apache.commons.beanutils.PropertyUtilsBean: int findNextNestedIndex(java.lang.String)>
<org.apache.commons.beanutils.converters.BigDecimalConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.BigIntegerConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.BooleanConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.ByteConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.CharacterConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.ClassConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.DoubleConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.FileConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.FloatConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.IntegerConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.LongConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.ShortConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.SqlDateConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.SqlTimeConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.SqlTimestampConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.StringConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.converters.URLConverter: java.lang.Object convert(java.lang.Class,java.lang.Object)>
<org.apache.commons.beanutils.locale.BaseLocaleConverter: void <clinit>()>
<org.apache.commons.beanutils.locale.LocaleBeanUtils: void <clinit>()>
<org.apache.commons.beanutils.locale.LocaleBeanUtils: java.lang.Class class$(java.lang.String)>
<org.apache.commons.beanutils.locale.converters.DateLocaleConverter: java.text.SimpleDateFormat getFormatter(java.lang.String,java.util.Locale)>
<org.apache.commons.beanutils.locale.converters.DecimalLocaleConverter: void <clinit>()>
<org.apache.commons.beanutils.locale.converters.StringLocaleConverter: void <clinit>()>

**Comment by javasoze** [comment]
latest no longer depend on hadoop which introduces this dependency.
